# Generated by Django 2.1.1 on 2018-10-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20181002_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.ManyToManyField(blank=True, to='card.Role'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='card.Status'),
        ),
    ]
