# Generated by Django 2.1.1 on 2018-10-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20181018_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.Collection'),
        ),
    ]
