# Generated by Django 2.1.1 on 2018-10-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20181023_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='card.Collection'),
        ),
    ]
