# Generated by Django 2.1.1 on 2018-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20181024_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='card',
            field=models.ManyToManyField(related_name='boards', to='card.Card'),
        ),
    ]
