# Generated by Django 2.1.1 on 2018-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20181026_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='card',
            field=models.ManyToManyField(blank=True, related_name='boards', to='card.Card'),
        ),
    ]
