# Generated by Django 2.1.1 on 2018-10-01 11:51

from django.db import migrations, models
import json

def load_data(apps, schema_editor):

    with open('status_data.json') as f:
        data = json.load(f)

    Status = apps.get_model('card', 'Status')

    for item in data:
        Status.objects.create(id=item.get("id"),
                              name=item.get("fields").get("name"),
                              is_active=item.get("fields").get("is_actuve"),
                              order_num=item.get("fields").get("order_num"),
                              is_default=item.get("fields").get("is_default"))



class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_actuve', models.BooleanField(default=True)),
                ('order_num', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(load_data),
    ]
